webrails/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :geolocations

=begin
  
  get "/geolocations" index
  post "/geolocations" create
  delete "/geolocations/:id" destroy
  get "/geolocations/:id" show
  get "/geolocations/new" new
  get "/geolocations/:id/edit"  edit
  patch "/geolocations/:id"  update
  put "/geolocations/:id" update
  
=end
  

  root 'welcome#index'

end

webrails/app/models/geolocation.rb
class Geolocation < ActiveRecord::Base
#para validar los campos
#presence valida que el elemento no este vacio

validates :title, presence: true, uniqueness: true
validates :body,  presence:true, length: {  minimum: 20 }
#validates : username , format: { with: /expresionregular/}
end

webrails/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

webrails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webrails/app/controllers/geolocations_controller.rb
class GeolocationsController < ApplicationController

	#GET /geolocations
	# Trae todos los registros 
	def index
		@geolocations=Geolocation.all
	end


	#GET geolotaions/:id
	def show
		#find encuentra un registro por su id
		#variable de tipo geolocation
		#params recibe todos los parametros que tiene id
		@geolocation = Geolocation.find(params[:id])
		# Geolocation.where(" body = ")
		# Geolocation.where("  id = ?, params[:id]")
		#Geolocation.where.not("id = ?", params[:id])
	end

	#GET /articles/new y todavia no esta en la bd
	def new
		@geolocation = Geolocation.new
	end

	def edit
		#encuentro el location que voy a editar
		@geolocation = Geolocation.find(params[:id])
	end

	#POST /geolocations
	def create
		@geolocation = Geolocation.new(geolocation_params)
	
    	#si el articulo pudo guardarse es por que las validaciones pasaron
		if @geolocation.save
			redirect_to @geolocation
		else
		   	render :new
		end
	end


	def destroy
		#elimina el objeto de la bd
		@geolocation = Geolocation.find(params[:id])
		@geolocation.destroy
		redirect_to geolocation_path
	end

	#si el objeto ya esta en la bd lo manda a update
	#PUT
	def update
		# @geolocation.update_attributes({title: 'Nuevo titulo'})
		@geolocation = Geolocation.find(params[:id])
		if @geolocation.update(geolocation_params)
			redirect_to @geolocation
		else
			render :edit
		end
	end

	#METODOS PRIVADOS DE LAS CLASES
	private
	def geolocation_params

		params.require(:geolocation).permit(:title,:body)
	
	end



end

webrails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

webrails/app/helpers/application_helper.rb
module ApplicationHelper
end

webrails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

webrails/app/views/geolocations/_form.html.erb
<%= form_for(@geolocation) do |f| %>

	<!--Cuantos errores impidieron que el articulo se guardara -->
		<% @geolocation.errors.full_messages.each do |message| %>
		<div class="be-errormessage red top-space">
			* <%= message %>
		</div>
		<%end%>

		<div class="field">
			<%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
		</div>

		<div class="field">
			<%= f.text_area :body, placeholder: "Escribe aqui", style:"height:250px;", class:"form-control" %>
		</div>

		<!--<div class="field">
			<%= f.submit "Guardar", class:"btn-guardar be-colorbtn white " %>
		</div>-->

		<div class="field">
         <%= f.submit "Guardar", class:"btn  white" %>
		</div>


	<% end %>

webrails/app/views/geolocations/edit.html.erb
<div style="width: 80%;margin:0 auto;">
	<h1>Editar articulo</h1>

<!-- aca hiba el codigo _form.html.erb -->
<!--carpeta donde esta el form/form -->
<%= render "form" %>
</div>

webrails/app/views/geolocations/index.html.erb
<% @geolocations.each do |geolocation| %>
<h1><%= link_to geolocation.title, geolocation %></h1>
<div>
	<%= geolocation.body %> - <%= link_to "Eliminar",geolocation,method: :delete%>
</div>
<%end%>

webrails/app/views/geolocations/new.html.erb
<div style="width: 80%;margin:0 auto;">
	<h1>Crear articulo</h1>
	<%= render "geolocations/form.html.erb" %>
</div>

webrails/app/views/geolocations/show.html.erb
<h1><%= @geolocation.title %></h1>

<div>
	<%= @geolocation.body %>
</div>

<div>
<%= link_to "Editar", edit_geolocation_path(@geolocation) %>
</div>

webrails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webrails</title>
  <link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<nav class="be-color white large-padding">
		<ul class="no-list  row center-xs middle-xs">

			<li class="col-md">
				<h1 class="no-margin" id="logo">Geolocation</h1>	
			</li>


			<li class="col-md"> 
			<!-- Me lleva ala pagina de inicio-->
			<%= link_to "Inicio", root_path %>
			</li>

			<li class="col-md">
			 	Equipo 
			</li>

			<li class="col-md">
			Mapa
			</li>

			<% if user_signed_in? %>
		
			<li class="col-md">
				<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
			</li>

			<%else%>

			<li class="col-md">
				<%= link_to "Iniciar sesion", new_user_session_path %>
			</li>

			<li class="col-md">
				<%= link_to "Crear Cuenta", new_user_registration_path %>
			</li>

			<%end%>


		</ul>
	</nav>
</header> 

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

webrails/app/views/welcome/index.html.erb
<h1>Bienvenidos a mi pagina web</h1>

<div style="width: 80%;margin:0 auto;">
	<h1>breve descripcion</h1>

	<h2>Cards usuario.css</h2>
	
</div>